import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

function syncDistPlugin() {
  return {
    name: "sync-dist",
    setup(build) {
      build.onEnd(() => {
        const distDir = "dist";
        const pluginDir = "dist/concrete";
        for (const dir of [distDir, pluginDir]) {
          if (!existsSync(dir)) {
            mkdirSync(dir, { recursive: true });
          }
        }
        for (const file of ["main.js", "manifest.json", "styles.css"]) {
          if (existsSync(file)) {
            copyFileSync(file, `${distDir}/${file}`);
            copyFileSync(file, `${pluginDir}/${file}`);
          }
        }
      });
    },
  };
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [syncDistPlugin()],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
